### ISSUE TITLE
Too many fixed effects?

### ISSUE THREAD

**Issue by sarahrosenberg** [kylebutts/did2s_stata#7]
I am trying to use did2s in Stata to estimate treatment effects for a sample where the observations are individual businesses observed in tax data over time, and the treatment is at the level of the individual business. As a result, in my full sample there are about 15,000 individual units (of which about two-thirds are ever-treated and the rest are never-treated) with about 250,000 period-unit observations in total.

The command runs (although it takes a couple hours) for subsamples that have up to about 9,000 restaurant observations, but Stata crashes within a few minutes of trying to do it for the full sample. I was wondering if you would have any guesses/intuition about what the limiting factor might be? Do you have an idea if it might be more likely to work in R?

**Comment by kylebutts** [comment]
Hi Sarah,

So the main reason did2s has difficulties with large data is calculating the analytic standard errors. I have to create the X matrix including the fixed effects which with so many units becomes a really large object (in this case large enough to fill up your RAM). In R I am able to surpass this a lot of the time by using sparse matrices (fixed effects have a lot of 0 entries, so sparse matrices don’t store these, freeing up a lot of memory).

Therefore I recommend two possible solutions:
1. You can try R version. You don’t need to know much R besides using the {haven} package to load a .dta file and running did2s().

2. You can use bootstrapped standard errors which does not require the creation of the model matrix. I have included an example using the dataset in the data/ folder:

```stata
use data/df_hom.dta, clear

egen unique_id = group(state unit)

capture program drop did2s_est

program did2s_est, rclass
    version 13.0
    regress dep_var i.new_id i.year if treat == 0
    tempvar dep_var_resid
    predict `dep_var_resid', residuals
    regress `dep_var_resid' ib0.treat
end

xtset unique_id year
sort unique_id year
bootstrap, cluster(state) idcluster(new_id) group(unique_id) reps(100): did2s_est
       panel variable:  unique_id (strongly balanced)
        time variable:  year, 1990 to 2020
                delta:  1 unit


(running did2s_est on estimation sample)

Bootstrap replications (100)
----+--- 1 ---+--- 2 ---+--- 3 ---+--- 4 ---+--- 5 
..................................................    50
..................................................   100

Linear regression                               Number of obs     =     31,000
                                                Replications      =        100
                                                Wald chi2(1)      =     739.20
                                                Prob > chi2       =     0.0000
                                                R-squared         =     0.2279
                                                Adj R-squared     =     0.2278
                                                Root MSE          =     1.7302

                                  (Replications based on 40 clusters in state)
------------------------------------------------------------------------------
             |   Observed   Bootstrap                         Normal-based
    __000001 |      Coef.   Std. Err.      z    P>|z|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
     1.treat |    1.98256   .0729197    27.19   0.000      1.83964     2.12548
       _cons |  -7.42e-11   4.03e-10    -0.18   0.854    -8.65e-10    7.16e-10
------------------------------------------------------------------------------
```

Unfortunately, this will be relatively slow because I can not use the reghdfe command as it can't predict residuals for observations not used in `e(sample)`, i.e. the treated observations.
