### ISSUE TITLE
Stata package does not drop always treated, R package does

### ISSUE THREAD

**Issue by ccmullally** [kylebutts/did2s_stata#8]
I've been playing around with both versions of did2s while creating problem sets in Stata and R for a class. I've found that the Stata package does not drop always-treated observations in estimation but the R package does. I'm happy to share the data set where you can see this in action.

**Comment by kylebutts** [comment]
Hi, thanks for pointing this out. I'm not really sure how or what Stata is doing for `predict var, residuals` then since the always treated unit FEs are not estimated in the first stage. In R, those observations would receive a value of `NA` so there is no need to manually drop them.

Since I don't require a `unit` argument, it's not possible to check this within the program. So, I suppose this is a case where individuals should manually drop always-treated observations before estimation (or with `if` argument)
